sudo: required
services:
  - docker
env:
    global:
    - PROJECT_ID="lab_wt"
    - IMAGE_NAME="app-demo:v2"
    - FULL_IMAGE_NAME=registry.cn-hangzhou.aliyuncs.com/$PROJECT_ID/$IMAGE_NAME
    - TRAVIS_SECURE_ENV_VARS=true
before_install:
    - docker build -t $FULL_IMAGE_NAME .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  registry.cn-hangzhou.aliyuncs.com
    - docker push $FULL_IMAGE_NAME
##deploy:
#  provider: script
#  script: bash docker_push.sh
#  on:
#    branch: master